GSAGH-512 Add Gerber Member demo file to oasys-sample-files repo
arup-group/oasys-sample-files pull request #15
Opened 2024-07-29 11:11 UTC by Abishek20Feb

2024-07-31 09:57 UTC, PeterDebneyOasys requested changes
I am getting laoding 
![image](https://github.com/user-attachments/assets/eb67af2a-ae79-4eef-a921-962b24bae611)
Object: CreateUnitNumber (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: CreateUnitNumber (level 2)
{
  Method not found: 'OasysUnits.Units.LengthUnit OasysGH.Units.DefaultUnits.get_LengthUnitGeometry()'.
  MissingMethodException
}

2024-08-02 14:32 UTC, PeterDebneyOasys commented
Please add description of what this model demonstrates, so that it can be tested and so we can also inform the users regarding the function, and also rename the file to match this function.

2025-04-17 21:27 UTC, PeterDebneyOasys requested changes
![image](https://github.com/user-attachments/assets/38685384-b751-4e3d-966a-e9fffe795170)
Please can we have the save file defaulted to the C:/temp folder as usual

2025-04-22 11:46 UTC, PeterDebneyOasys approved these changes

2025-05-09 05:07 UTC, KarthikAppakutti approved these changes

2025-05-12 10:31 UTC, merged