[GSAGH-545] Adding 4 point surface with mid-support demo file to oasys-sample-files
arup-group/oasys-sample-files pull request #19
Opened 2024-10-04 05:35 UTC by Abishek20Feb

This model file has a surface with 4 points and a mid-support added to the surface.
Galapagos solver is used to find the position of the mid support, which gives minimum 2D and nodal displacement.

2024-10-04 10:59 UTC, KarthikAppakutti requested changes
Please review the following points:

1. Why is it necessary to set up the restraints by exploding the curve?
2. Do we need to explicitly sort the nodal displacement?
3. What is the purpose of the script that selects colors and integers from the contours?

2024-10-29 05:07 UTC, KarthikAppakutti approved these changes

2024-11-12 12:18 UTC, PeterDebneyOasys requested changes
Please default the Galapagos object to Minimise

2024-11-19 12:13 UTC, PeterDebneyOasys approved these changes

2024-12-06 05:45 UTC, KarthikAppakutti approved these changes

2024-12-06 05:46 UTC, merged