Gsa 6836 validation fixes
arup-group/oasys-sample-files pull request #9
Opened 2023-09-06 14:40 UTC by PeterDebneyOasys

2023-09-07 18:51 UTC, angelahu005 requested changes
please update member 3 of 1D members.gwb so that the elements will pass the sync check.

2023-09-07 18:51 UTC, angelahu005 commented on gsa/10.2/General/1D members.gwb
this file still has sync issues.  However, if i delete the elements of member 3 and recreate the elements from members, the problem goes away.

2023-09-08 06:25 UTC, PeterDebneyOasys commented on gsa/10.2/General/1D members.gwb
@angelahu005 this model has revealed a bug in the creation / synchronization, so whatever we do at the moment, there will be an error report somewhere: https://ovearup.atlassian.net/browse/GSA-7376
Until that is fixed, does it matter which error is produced, or is there a version with a lesser error?

2023-09-08 07:03 UTC, PeterDebneyOasys commented on gsa/10.2/General/1D members.gwb
Meanwhile, I have recreated the elements and uploaded the updated model. It gives a sync warning on my copy of 10.2, but is that fixed on a more recent build...?

2023-09-08 14:10 UTC, angelahu005 commented on gsa/10.2/General/1D members.gwb
There is no sync issues when I open the updated model with 10.2.0.172

2023-09-08 14:10 UTC, angelahu005 approved these changes

2023-09-12 10:25 UTC, Abishek20Feb approved these changes

2023-09-12 10:26 UTC, merged